apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configMapName" . }}
  labels:
    app: {{ .Release.Name }}
data:
  USER_EVENT_READER_ADDRESS: {{ .Values.app.userEventReader.address | quote }}
  USER_EVENT_READER_TOPIC: {{ .Values.app.userEventReader.topic | quote }}
  USER_EVENT_READER_GROUP_ID: {{ .Values.app.userEventReader.groupId | quote }}
  HTTP_UID_HEADER: {{ .Values.app.httpUidHeader | quote }}
