apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configMapName" . }}
  labels:
    app: {{ .Release.Name }}
data:
  USER_EVENT_READER_BROKERS: {{ .Values.app.userEventReader.address | quote }}
  USER_EVENT_READER_TOPIC: {{ .Values.app.userEventReader.topic | quote }}
  USER_EVENT_READER_GROUP_ID: {{ .Values.app.userEventReader.groupId | quote }}

  # User ID header key
  UID_HEADER_KEY: {{ .Values.app.uidHeaderKey | quote }}

  INITIAL_NICKNAME_LENGTH: {{ .Values.app.initialNicknameLength | quote }}
  MAX_NICKNAME_RETRIES: {{ .Values.app.maxNicknameRetries | quote }}
