apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configMapName" . }}
  labels:
    app: {{ .Release.Name }}
data:
  USER_EVENT_WRITER_ADDRESS: {{ .Values.app.userEventWriter.address | quote }}
  USER_EVENT_WRITER_TOPIC: {{ .Values.app.userEventWriter.topic | quote }}
