apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configMapName" . }}
  labels:
    app: {{ .Release.Name }}
data:
  ACCESS_TOKEN_DURATION: {{ .Values.app.token.access.duration | quote }}
  REFRESH_TOKEN_DURATION: {{ .Values.app.token.refresh.duration | quote }}
  EMAIL_VERIFICATION_TOKEN_DURATION: {{ .Values.app.token.emailVerification.duration | quote }}
