apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.auth.configMapName" . }}
  labels:
    app: {{ .Release.Name }}
data:
  VERIFY_EMAIL_URL: {{ .Values.auth.verifyEmailUrl | quote }}

  LOGIN_CODE_STORE_PREFIX: {{ .Values.auth.loginCode.store.prefix | quote }}
  EMAIL_CODE_STORE_PREFIX: {{ .Values.auth.emailCode.store.prefix | quote }}

  SESSION_NAME: {{ .Values.auth.session.name | quote }}

  LOGIN_CODE_TTL: {{ .Values.auth.loginCode.ttl | quote }}
  EMAIL_CODE_TTL: {{ .Values.auth.emailCode.ttl | quote }}

  GOOGLE_REDIRECT_URL: {{ .Values.auth.oauth.google.redirectUrl | quote }}
  NAVER_REDIRECT_URL: {{ .Values.auth.oauth.naver.redirectUrl | quote }}
  KAKAO_REDIRECT_URL: {{ .Values.auth.oauth.kakao.redirectUrl | quote }}

  TOKEN_CLIENT_ADDR: {{ .Values.auth.tokenClient.address | quote }}

  MAIL_WRITER_ADDRESS: {{ .Values.auth.mailWriter.address | quote }}
  MAIL_WRITER_TOPIC: {{ .Values.auth.mailWriter.topic | quote }}

  USER_EVENT_READER_ADDRESS: {{ .Values.auth.userEventReader.address | quote }}
  USER_EVENT_READER_TOPIC: {{ .Values.auth.userEventReader.topic | quote }}
  USER_EVENT_READER_GROUP_ID: {{ .Values.auth.userEventReader.groupId | quote }}
