apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configMapName" . }}
  labels:
    app: {{ .Release.Name }}
data:
  KAFKA_ADDRESS: {{ .Values.app.kafka.address | quote }}
  KAFKA_TOPIC: {{ .Values.app.kafka.topic | quote }}
  KAFKA_GROUP_ID: {{ .Values.app.kafka.groupId | quote }}
  MAIL_SENDER: {{ .Values.app.smtp.sender | quote }}
