replicaCount: 1

nameOverride: ""
fullnameOverride: ""

database:
  existingSecret: ""
  host: "postgres"
  port: 5432
  name: "profile"
  sslMode: "disable"
  auth:
    username: ""
    password: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

imagePullSecrets:
  - name: regcred

migration:
  enabled: true
  image:
    repository: "registry.mandacode.com/accounts/user-migration"
    pullPolicy: "IfNotPresent"
    tag: "latest"

app:
  image:
    repository: "registry.mandacode.com/accounts/user"
    pullPolicy: "IfNotPresent"
    tag: "latest"

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

  service:
    http:
      type: "ClusterIP"
      port: 8080
      targetPort: 8080
    grpc:
      type: "ClusterIP"
      port: 50051
      targetPort: 50051

  userEventWriter:
    address: "kafka-event-bus:8080"
    topic: "user-event-topic"
